### ISSUE TITLE
Bug in StrawberryShake.Server v13.1.0 - The expression "[MSBuild]::VersionGreaterThanOrEquals('', 7)" cannot be evaluated. Version string was not in a correct format.

### ISSUE THREAD

**Issue by thomastvedt** [ChilliCream/graphql-platform#6224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

When upgrading `StrawberryShake.Server` from v13.0.5 to v13.1.0 I get a compilation error:

  StrawberryShake.Server.targets(38, 20): [MSB4184] The expression "[MSBuild]::VersionGreaterThanOrEquals('', 7)" cannot be evaluated. Version string was not in a correct format.

<img width="1289" alt="image" src="https://github.com/ChilliCream/graphql-platform/assets/4746639/9ea1a7ec-4cc9-4f9e-9aa2-243f2368a0d9">

It helps to run `dotnet graphql update`, but this shouldn't be necessary. Other users checking out the repo should not have to run any tool commands.

Found this related slack chat:
https://hotchocolategraphql.slack.com/archives/CMUJ40EHJ/p1685372432603619

### Steps to reproduce

1. Setup a project with StrawberryShake.Server v13.0.5
2. Upgrade to v13.1.0
3. Build project

### Additional Context?

.graphqlrc.json:

```json
{
  "schema": "schema.graphql",
  "documents": "**/*.graphql",
  "extensions": {
    "strawberryShake": {
      "name": "MyClient",
      "url": "https://localhost:5001/graphql/",
      "dependencyInjection": true,
      "strictSchemaValidation": true,
      "hashAlgorithm": "md5",
      "noStore": true,
      "emitGeneratedCode": false,
      "razorComponents": false,
      "records": {
        "inputs": false,
        "entities": false
      },
      "transportProfiles": [
        {
          "default": "Http",
          "subscription": "WebSocket"
        }
      ]
    }
  }
}
```

project.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<OutputType>Library</OutputType>
		<Authors>Company</Authors>
        <Company>Company</Company>
        <LangVersion>11</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
    <PackageReference Include="StrawberryShake.Server" Version="13.1.0" />
    <PackageReference Include="System.Reactive" Version="6.0.0" />
	<PackageReference Include="System.Reactive.Linq" Version="6.0.0" />

  </ItemGroup>
  
  <ItemGroup>
      <GraphQL Update="GraphQL\MyQuery.graphql">
        <Generator>MSBuild:Compile</Generator>
      </GraphQL>
    </ItemGroup>

</Project>

```

### Version

12.1.0

**Comment by thomastvedt** [comment]
Ahh.. duplicate:
https://github.com/ChilliCream/graphql-platform/issues/6180
https://github.com/ChilliCream/graphql-platform/issues/6048
